name: "Build SSSG site"
description: "Build a static site with SSSG"
branding:
  icon: "command"
  color: "orange"
inputs:
  source:
    description: "Source directory"
    required: true
  target:
    description: "Target directory"
  filesAsDirs:
    description: "Convert bare files to directories"
  ignorePaths:
    description: "Ignore paths (comma seperated)"
runs:
  using: "docker"
  image: "Dockerfile"
